--- #YAML:1.0
name:               movieinfo
version:            1.02
abstract:           get some basic movie file info
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Std::Strict:  1.01
    Image::Magick:        6.3.5
    LEOCHARRE::Basename:  1.06
    LEOCHARRE::Strings:   1.02
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
